apiVersion: apps/v1
kind: Deployment
metadata:
  name: captain-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captain-flask
  template:
    metadata:
      labels:
        app: captain-flask
    spec:
      containers:
      - name: captain-flask
        image: alexaaa902/captain-flask-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: captain-flask-service
spec:
  type: NodePort
  selector:
    app: captain-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
